import type { Metadata } from "next";
import { Noto_Serif as FontSans } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import HeaderComponent from "@/components/shared/header";
import { Web3Modal } from "@/context/web3modal";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const polyFont = FontSans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Etsy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased flex flex-col",
          fontSans.variable
        )}
      >
        <Web3Modal>
          <HeaderComponent />
          <main className="flex-1">{children}</main>
        </Web3Modal>
      </body>
    </html>
  );
}
